### ISSUE TITLE
Sometimes it hangs the browser on tabs with HTTP auth

### ISSUE THREAD

**Issue by aism** [tanwald/checkmarks#1]
Hi there,

Thank you for the useful add-on!

Sometimes when it opens a tab for webpage with HTTP Basic Auth, the entire browser hangs.
I tried to wait for timeout to expire but it doesn't help - only killing the FF process helps at this stage.
It doesn't happen every time though, i.e. even for the same webpage sometimes it gives me the chance to enter the creds, but sometimes it hangs the browser.

Unfortunately, I cannot give you an example webpage since all of such bookmarks I have are for corporate intranet.

FF 59.0.1 on macOS High Sierra 10.13.3 (17D102).

**Comment by tanwald** [comment]
Hi,

thanks for the feedback. I hope that I have fixed this issue with the latest update. Requests with basic auth should be cancelled.  I put intranet bookmarks into a separate folder and exclude this folder on the options page...

Best, Paul
