### ISSUE TITLE
Persist results / pause search

### ISSUE THREAD

**Issue by serenditree** [tanwald/checkmarks#4]
Hello Tanwald,

first a pile of thanx for checkmarks. Really useful tool to reload favicons and check broken marks - the best out there!

One suggestion: I have 6000 marks und checking them takes something like 90 minutes. Then I have 1000 broken links. I cant´t work them over in one session - but there is no option to save the results - especially the broken marks - or the whole analysis, and to reload it the next day. So I would have to start over and wait again for 90 min. 

So: Could there be an option to save the serach results and to reload them on another session?

Thanks for the great job till now!!!

Radim

_Originally posted by @ravall66 in https://github.com/tanwald/checkmarks/issues/3#issuecomment-466021946_

**Comment by serenditree** [comment]
Thanks for the suggestion @ravall66. It's on my list but time is rare. At the moment you can workaround by going to the settings page of the addon, activate "included directories" and enter a subset of your directories.

**Comment by Gitoffthelawn** [comment]
> So: Could there be an option to save the serach results and to reload them on another session?

I'm not sure if this is implied, but also a "pause" mechanism, please.

Thanks!

**Comment by tanwald** [comment]
Pause/resume is implemented in the latest version. If not manually discarded, results of complete or paused runs are persisted across sessions.
