### ISSUE TITLE
FR: add an option to renew the favicon of the active tab

### ISSUE THREAD

**Issue by Aybee** [tanwald/checkmarks#6]
Thank you for this extension.

I'm a web developer and often I change the favicon.ico within the root of an installation. So I was searching for an addon that updates the favicon on the active tab. Unfortunately checkmarks can not handle this. Can you please add such an option.

Here is a link to a page explaining how to force Firefox to reload a favicon. My attempts to delete the data in the favicons.sqlite were unsuccessful.

https://www.pctipp.ch/tipps-tricks/kummerkasten/internet/artikel/firefox-neu-laden-des-favicons-erzwingen-90189/

**Comment by tanwald** [comment]
Hi, thanks for the feedback and your hint. I've added an option to clear cache before run. In combination with the option "Included directories contain:" this should do the trick. Just collect your projects into a distinct folder and insert its name in the options input field. Each time you press play, cache will be cleared before the bookmarks within the folder are reloaded...

**Comment by Aybee** [comment]
Thank you very much. I will try this.
